<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('security_countries', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100);
            $table->string('dial_code', 10);
            $table->string('iso2', 10)->unique();
            $table->boolean('default', 10);
        });

        DB::table('security_countries')->insert([
            ["name" => "Afganistán", "dial_code" => "+93", "iso2" => "af", "default" => 0],
            ["name" => "Albania", "dial_code" => "+355", "iso2" => "al", "default" => 0],
            ["name" => "Alemania", "dial_code" => "+49", "iso2" => "de", "default" => 0],
            ["name" => "Andorra", "dial_code" => "+376", "iso2" => "ad", "default" => 0],
            ["name" => "Angola", "dial_code" => "+244", "iso2" => "ao", "default" => 0],
            ["name" => "Anguila", "dial_code" => "+1", "iso2" => "ai", "default" => 0],
            ["name" => "Antigua y Barbuda", "dial_code" => "+1", "iso2" => "ag", "default" => 0],
            ["name" => "Arabia Saudí", "dial_code" => "+966", "iso2" => "sa", "default" => 0],
            ["name" => "Argelia", "dial_code" => "+213", "iso2" => "dz", "default" => 0],
            ["name" => "Argentina", "dial_code" => "+54", "iso2" => "ar", "default" => 0],
            ["name" => "Armenia", "dial_code" => "+374", "iso2" => "am", "default" => 0],
            ["name" => "Aruba", "dial_code" => "+297", "iso2" => "aw", "default" => 0],
            ["name" => "Ascension Island", "dial_code" => "+247", "iso2" => "ac", "default" => 0],
            ["name" => "Australia", "dial_code" => "+61", "iso2" => "au", "default" => 0],
            ["name" => "Austria", "dial_code" => "+43", "iso2" => "at", "default" => 0],
            ["name" => "Azerbaiyán", "dial_code" => "+994", "iso2" => "az", "default" => 0],
            ["name" => "Bahamas", "dial_code" => "+1", "iso2" => "bs", "default" => 0],
            ["name" => "Bangladés", "dial_code" => "+880", "iso2" => "bd", "default" => 0],
            ["name" => "Barbados", "dial_code" => "+1", "iso2" => "bb", "default" => 0],
            ["name" => "Baréin", "dial_code" => "+973", "iso2" => "bh", "default" => 0],
            ["name" => "Bélgica", "dial_code" => "+32", "iso2" => "be", "default" => 0],
            ["name" => "Belice", "dial_code" => "+5git pull origin feature/develop_cl01", "iso2" => "bz", "default" => 0],
            ["name" => "Benín", "dial_code" => "+229", "iso2" => "bj", "default" => 0],
            ["name" => "Bermudas", "dial_code" => "+1", "iso2" => "bm", "default" => 0],
            ["name" => "Bielorrusia", "dial_code" => "+375", "iso2" => "by", "default" => 0],
            ["name" => "Bolivia", "dial_code" => "+591", "iso2" => "bo", "default" => 0],
            ["name" => "Bosnia y Herzegovina", "dial_code" => "+387", "iso2" => "ba", "default" => 0],
            ["name" => "Botsuana", "dial_code" => "+267", "iso2" => "bw", "default" => 0],
            ["name" => "Brasil", "dial_code" => "+55", "iso2" => "br", "default" => 0],
            ["name" => "Brunéi", "dial_code" => "+673", "iso2" => "bn", "default" => 0],
            ["name" => "Bulgaria", "dial_code" => "+359", "iso2" => "bg", "default" => 0],
            ["name" => "Burkina Faso", "dial_code" => "+226", "iso2" => "bf", "default" => 0],
            ["name" => "Burundi", "dial_code" => "+257", "iso2" => "bi", "default" => 0],
            ["name" => "Bután", "dial_code" => "+975", "iso2" => "bt", "default" => 0],
            ["name" => "Cabo Verde", "dial_code" => "+238", "iso2" => "cv", "default" => 0],
            ["name" => "Camboya", "dial_code" => "+855", "iso2" => "kh", "default" => 0],
            ["name" => "Camerún", "dial_code" => "+237", "iso2" => "cm", "default" => 0],
            ["name" => "Canadá", "dial_code" => "+1", "iso2" => "ca", "default" => 0],
            ["name" => "Caribe neerlandés", "dial_code" => "+599", "iso2" => "bq", "default" => 0],
            ["name" => "Catar", "dial_code" => "+974", "iso2" => "qa", "default" => 0],
            ["name" => "Chad", "dial_code" => "+235", "iso2" => "td", "default" => 0],
            ["name" => "Chequia", "dial_code" => "+420", "iso2" => "cz", "default" => 0],
            ["name" => "Chile", "dial_code" => "+56", "iso2" => "cl", "default" => 0],
            ["name" => "China", "dial_code" => "+86", "iso2" => "cn", "default" => 0],
            ["name" => "Chipre", "dial_code" => "+357", "iso2" => "cy", "default" => 0],
            ["name" => "Ciudad del Vaticano", "dial_code" => "+39", "iso2" => "va", "default" => 0],
            ["name" => "Colombia", "dial_code" => "+57", "iso2" => "co", "default" => 0],
            ["name" => "Comoras", "dial_code" => "+269", "iso2" => "km", "default" => 0],
            ["name" => "Congo", "dial_code" => "+242", "iso2" => "cg", "default" => 0],
            ["name" => "Corea del Norte", "dial_code" => "+850", "iso2" => "kp", "default" => 0],
            ["name" => "Corea del Sur", "dial_code" => "+82", "iso2" => "kr", "default" => 0],
            ["name" => "Costa Rica", "dial_code" => "+506", "iso2" => "cr", "default" => 0],
            ["name" => "Côte d’Ivoire", "dial_code" => "+225", "iso2" => "ci", "default" => 0],
            ["name" => "Croacia", "dial_code" => "+385", "iso2" => "hr", "default" => 0],
            ["name" => "Cuba", "dial_code" => "+53", "iso2" => "cu", "default" => 0],
            ["name" => "Curazao", "dial_code" => "+599", "iso2" => "cw", "default" => 0],
            ["name" => "Dinamarca", "dial_code" => "+45", "iso2" => "dk", "default" => 0],
            ["name" => "Dominica", "dial_code" => "+1", "iso2" => "dm", "default" => 0],
            ["name" => "Ecuador", "dial_code" => "+593", "iso2" => "ec", "default" => 0],
            ["name" => "Egipto", "dial_code" => "+20", "iso2" => "eg", "default" => 0],
            ["name" => "El Salvador", "dial_code" => "+503", "iso2" => "sv", "default" => 0],
            ["name" => "Emiratos Árabes Unidos", "dial_code" => "+971", "iso2" => "ae", "default" => 0],
            ["name" => "Eritrea", "dial_code" => "+291", "iso2" => "er", "default" => 0],
            ["name" => "Eslovaquia", "dial_code" => "+421", "iso2" => "sk", "default" => 0],
            ["name" => "Eslovenia", "dial_code" => "+386", "iso2" => "si", "default" => 0],
            ["name" => "España", "dial_code" => "+34", "iso2" => "es", "default" => 0],
            ["name" => "Estados Unidos", "dial_code" => "+1", "iso2" => "us", "default" => 0],
            ["name" => "Estonia", "dial_code" => "+372", "iso2" => "ee", "default" => 0],
            ["name" => "Esuatini", "dial_code" => "+268", "iso2" => "sz", "default" => 0],
            ["name" => "Etiopía", "dial_code" => "+251", "iso2" => "et", "default" => 0],
            ["name" => "Filipinas", "dial_code" => "+63", "iso2" => "ph", "default" => 0],
            ["name" => "Finlandia", "dial_code" => "+358", "iso2" => "fi", "default" => 0],
            ["name" => "Fiyi", "dial_code" => "+679", "iso2" => "fj", "default" => 0],
            ["name" => "Francia", "dial_code" => "+33", "iso2" => "fr", "default" => 0],
            ["name" => "Gabón", "dial_code" => "+241", "iso2" => "ga", "default" => 0],
            ["name" => "Gambia", "dial_code" => "+220", "iso2" => "gm", "default" => 0],
            ["name" => "Georgia", "dial_code" => "+995", "iso2" => "ge", "default" => 0],
            ["name" => "Ghana", "dial_code" => "+233", "iso2" => "gh", "default" => 0],
            ["name" => "Gibraltar", "dial_code" => "+350", "iso2" => "gi", "default" => 0],
            ["name" => "Granada", "dial_code" => "+1", "iso2" => "gd", "default" => 0],
            ["name" => "Grecia", "dial_code" => "+30", "iso2" => "gr", "default" => 0],
            ["name" => "Groenlandia", "dial_code" => "+299", "iso2" => "gl", "default" => 0],
            ["name" => "Guadalupe", "dial_code" => "+590", "iso2" => "gp", "default" => 0],
            ["name" => "Guam", "dial_code" => "+1", "iso2" => "gu", "default" => 0],
            ["name" => "Guatemala", "dial_code" => "+502", "iso2" => "gt", "default" => 0],
            ["name" => "Guayana Francesa", "dial_code" => "+594", "iso2" => "gf", "default" => 0],
            ["name" => "Guernsey", "dial_code" => "+44", "iso2" => "gg", "default" => 0],
            ["name" => "Guinea", "dial_code" => "+224", "iso2" => "gn", "default" => 0],
            ["name" => "Guinea Ecuatorial", "dial_code" => "+240", "iso2" => "gq", "default" => 0],
            ["name" => "Guinea-Bisáu", "dial_code" => "+245", "iso2" => "gw", "default" => 0],
            ["name" => "Guyana", "dial_code" => "+592", "iso2" => "gy", "default" => 0],
            ["name" => "Haití", "dial_code" => "+509", "iso2" => "ht", "default" => 0],
            ["name" => "Honduras", "dial_code" => "+504", "iso2" => "hn", "default" => 0],
            ["name" => "Hungría", "dial_code" => "+36", "iso2" => "hu", "default" => 0],
            ["name" => "India", "dial_code" => "+91", "iso2" => "in", "default" => 0],
            ["name" => "Indonesia", "dial_code" => "+62", "iso2" => "id", "default" => 0],
            ["name" => "Irak", "dial_code" => "+964", "iso2" => "iq", "default" => 0],
            ["name" => "Irán", "dial_code" => "+98", "iso2" => "ir", "default" => 0],
            ["name" => "Irlanda", "dial_code" => "+353", "iso2" => "ie", "default" => 0],
            ["name" => "Isla de Man", "dial_code" => "+44", "iso2" => "im", "default" => 0],
            ["name" => "Isla de Navidad", "dial_code" => "+61", "iso2" => "cx", "default" => 0],
            ["name" => "Isla Norfolk", "dial_code" => "+672", "iso2" => "nf", "default" => 0],
            ["name" => "Islandia", "dial_code" => "+354", "iso2" => "is", "default" => 0],
            ["name" => "Islas Åland", "dial_code" => "+358", "iso2" => "ax", "default" => 0],
            ["name" => "Islas Caimán", "dial_code" => "+1", "iso2" => "ky", "default" => 0],
            ["name" => "Islas Cocos", "dial_code" => "+61", "iso2" => "cc", "default" => 0],
            ["name" => "Islas Cook", "dial_code" => "+682", "iso2" => "ck", "default" => 0],
            ["name" => "Islas Feroe", "dial_code" => "+298", "iso2" => "fo", "default" => 0],
            ["name" => "Islas Malvinas", "dial_code" => "+500", "iso2" => "fk", "default" => 0],
            ["name" => "Islas Marianas del Norte", "dial_code" => "+1", "iso2" => "mp", "default" => 0],
            ["name" => "Islas Marshall", "dial_code" => "+692", "iso2" => "mh", "default" => 0],
            ["name" => "Islas Salomón", "dial_code" => "+677", "iso2" => "sb", "default" => 0],
            ["name" => "Islas Turcas y Caicos", "dial_code" => "+1", "iso2" => "tc", "default" => 0],
            ["name" => "Islas Vírgenes Británicas", "dial_code" => "+1", "iso2" => "vg", "default" => 0],
            ["name" => "Islas Vírgenes de EE. UU.", "dial_code" => "+1", "iso2" => "vi", "default" => 0],
            ["name" => "Israel", "dial_code" => "+972", "iso2" => "il", "default" => 0],
            ["name" => "Italia", "dial_code" => "+39", "iso2" => "it", "default" => 0],
            ["name" => "Jamaica", "dial_code" => "+1", "iso2" => "jm", "default" => 0],
            ["name" => "Japón", "dial_code" => "+81", "iso2" => "jp", "default" => 0],
            ["name" => "Jersey", "dial_code" => "+44", "iso2" => "je", "default" => 0],
            ["name" => "Jordania", "dial_code" => "+962", "iso2" => "jo", "default" => 0],
            ["name" => "Kazajistán", "dial_code" => "+7", "iso2" => "kz", "default" => 0],
            ["name" => "Kenia", "dial_code" => "+254", "iso2" => "ke", "default" => 0],
            ["name" => "Kirguistán", "dial_code" => "+996", "iso2" => "kg", "default" => 0],
            ["name" => "Kiribati", "dial_code" => "+686", "iso2" => "ki", "default" => 0],
            ["name" => "Kosovo", "dial_code" => "+383", "iso2" => "xk", "default" => 0],
            ["name" => "Kuwait", "dial_code" => "+965", "iso2" => "kw", "default" => 0],
            ["name" => "Laos", "dial_code" => "+856", "iso2" => "la", "default" => 0],
            ["name" => "Lesoto", "dial_code" => "+266", "iso2" => "ls", "default" => 0],
            ["name" => "Letonia", "dial_code" => "+371", "iso2" => "lv", "default" => 0],
            ["name" => "Líbano", "dial_code" => "+961", "iso2" => "lb", "default" => 0],
            ["name" => "Liberia", "dial_code" => "+231", "iso2" => "lr", "default" => 0],
            ["name" => "Libia", "dial_code" => "+218", "iso2" => "ly", "default" => 0],
            ["name" => "Liechtenstein", "dial_code" => "+423", "iso2" => "li", "default" => 0],
            ["name" => "Lituania", "dial_code" => "+370", "iso2" => "lt", "default" => 0],
            ["name" => "Luxemburgo", "dial_code" => "+352", "iso2" => "lu", "default" => 0],
            ["name" => "Macedonia del Norte", "dial_code" => "+389", "iso2" => "mk", "default" => 0],
            ["name" => "Madagascar", "dial_code" => "+261", "iso2" => "mg", "default" => 0],
            ["name" => "Malasia", "dial_code" => "+60", "iso2" => "my", "default" => 0],
            ["name" => "Malaui", "dial_code" => "+265", "iso2" => "mw", "default" => 0],
            ["name" => "Maldivas", "dial_code" => "+960", "iso2" => "mv", "default" => 0],
            ["name" => "Mali", "dial_code" => "+223", "iso2" => "ml", "default" => 0],
            ["name" => "Malta", "dial_code" => "+356", "iso2" => "mt", "default" => 0],
            ["name" => "Marruecos", "dial_code" => "+212", "iso2" => "ma", "default" => 0],
            ["name" => "Martinica", "dial_code" => "+596", "iso2" => "mq", "default" => 0],
            ["name" => "Mauricio", "dial_code" => "+230", "iso2" => "mu", "default" => 0],
            ["name" => "Mauritania", "dial_code" => "+222", "iso2" => "mr", "default" => 0],
            ["name" => "Mayotte", "dial_code" => "+262", "iso2" => "yt", "default" => 0],
            ["name" => "México", "dial_code" => "+52", "iso2" => "mx", "default" => 0],
            ["name" => "Micronesia", "dial_code" => "+691", "iso2" => "fm", "default" => 0],
            ["name" => "Moldavia", "dial_code" => "+373", "iso2" => "md", "default" => 0],
            ["name" => "Mónaco", "dial_code" => "+377", "iso2" => "mc", "default" => 0],
            ["name" => "Mongolia", "dial_code" => "+976", "iso2" => "mn", "default" => 0],
            ["name" => "Montenegro", "dial_code" => "+382", "iso2" => "me", "default" => 0],
            ["name" => "Montserrat", "dial_code" => "+1", "iso2" => "ms", "default" => 0],
            ["name" => "Mozambique", "dial_code" => "+258", "iso2" => "mz", "default" => 0],
            ["name" => "Myanmar (Birmania)", "dial_code" => "+95", "iso2" => "mm", "default" => 0],
            ["name" => "Namibia", "dial_code" => "+264", "iso2" => "na", "default" => 0],
            ["name" => "Nauru", "dial_code" => "+674", "iso2" => "nr", "default" => 0],
            ["name" => "Nepal", "dial_code" => "+977", "iso2" => "np", "default" => 0],
            ["name" => "Nicaragua", "dial_code" => "+505", "iso2" => "ni", "default" => 0],
            ["name" => "Níger", "dial_code" => "+227", "iso2" => "ne", "default" => 0],
            ["name" => "Nigeria", "dial_code" => "+234", "iso2" => "ng", "default" => 0],
            ["name" => "Niue", "dial_code" => "+683", "iso2" => "nu", "default" => 0],
            ["name" => "Noruega", "dial_code" => "+47", "iso2" => "no", "default" => 0],
            ["name" => "Nueva Caledonia", "dial_code" => "+687", "iso2" => "nc", "default" => 0],
            ["name" => "Nueva Zelanda", "dial_code" => "+64", "iso2" => "nz", "default" => 0],
            ["name" => "Omán", "dial_code" => "+968", "iso2" => "om", "default" => 0],
            ["name" => "Países Bajos", "dial_code" => "+31", "iso2" => "nl", "default" => 0],
            ["name" => "Pakistán", "dial_code" => "+92", "iso2" => "pk", "default" => 0],
            ["name" => "Palaos", "dial_code" => "+680", "iso2" => "pw", "default" => 0],
            ["name" => "Panamá", "dial_code" => "+507", "iso2" => "pa", "default" => 0],
            ["name" => "Papúa Nueva Guinea", "dial_code" => "+675", "iso2" => "pg", "default" => 0],
            ["name" => "Paraguay", "dial_code" => "+595", "iso2" => "py", "default" => 0],
            ["name" => "Perú", "dial_code" => "+51", "iso2" => "pe", "default" => 0],
            ["name" => "Polinesia Francesa", "dial_code" => "+689", "iso2" => "pf", "default" => 0],
            ["name" => "Polonia", "dial_code" => "+48", "iso2" => "pl", "default" => 0],
            ["name" => "Portugal", "dial_code" => "+351", "iso2" => "pt", "default" => 0],
            ["name" => "Puerto Rico", "dial_code" => "+1", "iso2" => "pr", "default" => 0],
            ["name" => "RAE de Hong Kong (China)", "dial_code" => "+852", "iso2" => "hk", "default" => 0],
            ["name" => "RAE de Macao (China)", "dial_code" => "+853", "iso2" => "mo", "default" => 0],
            ["name" => "Reino Unido", "dial_code" => "+44", "iso2" => "gb", "default" => 0],
            ["name" => "República Centroafricana", "dial_code" => "+236", "iso2" => "cf", "default" => 0],
            ["name" => "República Democrática del Congo", "dial_code" => "+243", "iso2" => "cd", "default" => 0],
            ["name" => "República Dominicana", "dial_code" => "+1", "iso2" => "do", "default" => 0],
            ["name" => "Reunión", "dial_code" => "+262", "iso2" => "re", "default" => 0],
            ["name" => "Ruanda", "dial_code" => "+250", "iso2" => "rw", "default" => 0],
            ["name" => "Rumanía", "dial_code" => "+40", "iso2" => "ro", "default" => 0],
            ["name" => "Rusia", "dial_code" => "+7", "iso2" => "ru", "default" => 0],
            ["name" => "Sáhara Occidental", "dial_code" => "+212", "iso2" => "eh", "default" => 0],
            ["name" => "Samoa", "dial_code" => "+685", "iso2" => "ws", "default" => 0],
            ["name" => "Samoa Americana", "dial_code" => "+1", "iso2" => "as", "default" => 0],
            ["name" => "San Bartolomé", "dial_code" => "+590", "iso2" => "bl", "default" => 0],
            ["name" => "San Cristóbal y Nieves", "dial_code" => "+1", "iso2" => "kn", "default" => 0],
            ["name" => "San Marino", "dial_code" => "+378", "iso2" => "sm", "default" => 0],
            ["name" => "San Martín", "dial_code" => "+590", "iso2" => "mf", "default" => 0],
            ["name" => "San Pedro y Miquelón", "dial_code" => "+508", "iso2" => "pm", "default" => 0],
            ["name" => "San Vicente y las Granadinas", "dial_code" => "+1", "iso2" => "vc", "default" => 0],
            ["name" => "Santa Elena", "dial_code" => "+290", "iso2" => "sh", "default" => 0],
            ["name" => "Santa Lucía", "dial_code" => "+1", "iso2" => "lc", "default" => 0],
            ["name" => "Santo Tomé y Príncipe", "dial_code" => "+239", "iso2" => "st", "default" => 0],
            ["name" => "Senegal", "dial_code" => "+221", "iso2" => "sn", "default" => 0],
            ["name" => "Serbia", "dial_code" => "+381", "iso2" => "rs", "default" => 0],
            ["name" => "Seychelles", "dial_code" => "+248", "iso2" => "sc", "default" => 0],
            ["name" => "Sierra Leona", "dial_code" => "+232", "iso2" => "sl", "default" => 0],
            ["name" => "Singapur", "dial_code" => "+65", "iso2" => "sg", "default" => 0],
            ["name" => "Sint Maarten", "dial_code" => "+1", "iso2" => "sx", "default" => 0],
            ["name" => "Siria", "dial_code" => "+963", "iso2" => "sy", "default" => 0],
            ["name" => "Somalia", "dial_code" => "+252", "iso2" => "so", "default" => 0],
            ["name" => "Sri Lanka", "dial_code" => "+94", "iso2" => "lk", "default" => 0],
            ["name" => "Sudáfrica", "dial_code" => "+27", "iso2" => "za", "default" => 0],
            ["name" => "Sudán", "dial_code" => "+249", "iso2" => "sd", "default" => 0],
            ["name" => "Sudán del Sur", "dial_code" => "+211", "iso2" => "ss", "default" => 0],
            ["name" => "Suecia", "dial_code" => "+46", "iso2" => "se", "default" => 0],
            ["name" => "Suiza", "dial_code" => "+41", "iso2" => "ch", "default" => 0],
            ["name" => "Surinam", "dial_code" => "+597", "iso2" => "sr", "default" => 0],
            ["name" => "Svalbard y Jan Mayen", "dial_code" => "+47", "iso2" => "sj", "default" => 0],
            ["name" => "Tailandia", "dial_code" => "+66", "iso2" => "th", "default" => 0],
            ["name" => "Taiwán", "dial_code" => "+886", "iso2" => "tw", "default" => 0],
            ["name" => "Tanzania", "dial_code" => "+255", "iso2" => "tz", "default" => 0],
            ["name" => "Tayikistán", "dial_code" => "+992", "iso2" => "tj", "default" => 0],
            ["name" => "Territorio Británico del Océano Índico", "dial_code" => "+246", "iso2" => "io", "default" => 0],
            ["name" => "Territorios Palestinos", "dial_code" => "+970", "iso2" => "ps", "default" => 0],
            ["name" => "Timor-Leste", "dial_code" => "+670", "iso2" => "tl", "default" => 0],
            ["name" => "Togo", "dial_code" => "+228", "iso2" => "tg", "default" => 0],
            ["name" => "Tokelau", "dial_code" => "+690", "iso2" => "tk", "default" => 0],
            ["name" => "Tonga", "dial_code" => "+676", "iso2" => "to", "default" => 0],
            ["name" => "Trinidad y Tobago", "dial_code" => "+1", "iso2" => "tt", "default" => 0],
            ["name" => "Túnez", "dial_code" => "+216", "iso2" => "tn", "default" => 0],
            ["name" => "Turkmenistán", "dial_code" => "+993", "iso2" => "tm", "default" => 0],
            ["name" => "Turquía", "dial_code" => "+90", "iso2" => "tr", "default" => 0],
            ["name" => "Tuvalu", "dial_code" => "+688", "iso2" => "tv", "default" => 0],
            ["name" => "Ucrania", "dial_code" => "+380", "iso2" => "ua", "default" => 0],
            ["name" => "Uganda", "dial_code" => "+256", "iso2" => "ug", "default" => 0],
            ["name" => "Uruguay", "dial_code" => "+598", "iso2" => "uy", "default" => 0],
            ["name" => "Uzbekistán", "dial_code" => "+998", "iso2" => "uz", "default" => 0],
            ["name" => "Vanuatu", "dial_code" => "+678", "iso2" => "vu", "default" => 0],
            ["name" => "Venezuela", "dial_code" => "+58", "iso2" => "ve", "default" => 1],
            ["name" => "Vietnam", "dial_code" => "+84", "iso2" => "vn", "default" => 0],
            ["name" => "Wallis y Futuna", "dial_code" => "+681", "iso2" => "wf", "default" => 0],
            ["name" => "Yemen", "dial_code" => "+967", "iso2" => "ye", "default" => 0],
            ["name" => "Yibuti", "dial_code" => "+253", "iso2" => "dj", "default" => 0],
            ["name" => "Zambia", "dial_code" => "+260", "iso2" => "zm", "default" => 0],
            ["name" => "Zimbabue", "dial_code" => "+263", "iso2" => "zw", "default" => 0]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('security_countries');
    }
};
