<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('comun_personas', function (Blueprint $table) {
            // Clave Primaria
            $table->id(); // "id_persona" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

            // Columnas de Identificación y Datos Personales
        //    $table->string('tipo_persona')->nullable(); // "tipo_persona" varchar
            
            // Llaves Foráneas (se usa unsignedBigInteger para referenciar IDs de otras tablas)
        //    $table->unsignedBigInteger('tipo_dni')->nullable(); // "tipo_dni" int (FK a security_document_types)
            
            $table->string('document')->nullable(); // "dni" varchar
        //    $table->string('pasaporte')->nullable(); // "pasaporte" varchar
        //    $table->string('rif')->nullable(); // "rif" varchar
        //    $table->string('registro_cnac')->nullable(); // "Reg_cnac" varchar
            
            // Llave Foránea
        //    $table->unsignedBigInteger('genero')->nullable(); // "genero" int (FK a security_genders)
            
            $table->string('primer_nombre')->nullable(); // "primer_nombre" varchar
            $table->string('segundo_nombre')->nullable(); // "segundo_nombre" varchar
            $table->string('primer_apellido')->nullable(); // "primer_apellido" varchar
            $table->string('segundo_apellido')->nullable(); // "segundo_apellido" varchar
            
            // Columnas de Contacto y Verificación
        //    $table->string('email')->nullable(); // "email" varchar
        //    $table->boolean('email_verificado')->nullable(); // "email_verificado" boolean
        //    $table->string('token_verificacion_email')->nullable(); // "token_verificacion_email" varchar
        //    $table->string('telefono')->nullable(); // "telefono" varchar
        //    $table->string('telefono_opcional')->nullable(); // "telefono_opcional" varchar
            
            // Llaves Foráneas de Ubicación
        //    $table->unsignedBigInteger('idPais')->nullable(); // "idPais" int
        //    $table->unsignedBigInteger('idEstado')->nullable(); // "idEstado" int
        //    $table->unsignedBigInteger('idCiudad')->nullable(); // "idCiudad" int
        //    $table->unsignedBigInteger('idMunicipio')->nullable(); // "idMunicipio" int
            // Nota: Se asume que idParroquia es de tipo entero para FK
        //    $table->unsignedBigInteger('idParroquia')->nullable(); // "idParroquia" int (o varchar, según tu archivo security.sql)

        //    $table->string('direccion')->nullable(); // "direccion" varchar
            
            // Columnas de Auditoría (definidas como datetime en tu SQL)
        //    $table->integer('creado_por')->nullable();
        //    $table->dateTime('creado_en')->nullable(); 
        //    $table->integer('actualizado_por')->nullable();
        //    $table->dateTime('actualizado_en')->nullable();
        });

        DB::table('comun_personas')->insert([
            [
                'primer_nombre' => 'admin',
                'segundo_nombre' => 'admin',
                'primer_apellido' => 'admin',
                'segundo_apellido' => 'admin',
                'document' => '99999999',
                
            ],  
            [
                'primer_nombre' => 'Cristhofer',
                'segundo_nombre' => 'Luis',
                'primer_apellido' => 'Leon',
                'segundo_apellido' => 'Gonzalez',
                'document' => '30098588',
              
            ],
            [
                'primer_nombre' => 'Zoe',
                'segundo_nombre' => 'Anais',
                'primer_apellido' => 'Medina',
                'segundo_apellido' => 'Quintero',
                'document' => '29310488',
              
            ],
            [
                'primer_nombre' => 'Pedro',
                'segundo_nombre' => 'Julian',
                'primer_apellido' => 'Leon',
                'segundo_apellido' => 'Gonzales',
                'document' => '12345678',
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('comun_personas');
    }
};