<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('comun.municipios', function (Blueprint $table) {
            $table->increments('id_municipio');
            $table->string('nombre', 100);
            $table->unsignedInteger('id_estado');
            $table->integer('creado_por')->nullable();
            $table->timestamp('creado_en')->nullable();
            $table->integer('actualizado_por')->nullable();
            $table->timestamp('actualizado_en')->nullable();
                
            $table->foreign('id_estado')->references('id_estado')->on('comun.estados')->onDelete('cascade');
        });

         DB::table('comun.municipios')->insert([
            [ 'id_municipio' => 1 , 'nombre' => 'Alto Orinoco', 'id_estado' => 1 ],
            [ 'id_municipio' => 2 , 'nombre' =>'Atabapo', 'id_estado' => 1 ],
            [ 'id_municipio' => 3 , 'nombre' =>'Atures', 'id_estado' => 1 ],
            [ 'id_municipio' => 4 , 'nombre' =>'Autana', 'id_estado' => 1 ],
            [ 'id_municipio' => 5 , 'nombre' =>'Manapiare', 'id_estado' => 1 ],
            [ 'id_municipio' => 6 , 'nombre' =>'Río Negro', 'id_estado' => 1 ],
            [ 'id_municipio' => 7 , 'nombre' =>'Anaco', 'id_estado' => 2 ],
            [ 'id_municipio' => 8 , 'nombre' =>'Aragua', 'id_estado' => 2 ],
            [ 'id_municipio' => 9 , 'nombre' =>'Bolívar', 'id_estado' => 2 ],
            [ 'id_municipio' => 10 , 'nombre' =>'Brion', 'id_estado' => 2 ],
            [ 'id_municipio' => 11 , 'nombre' =>'Cantaura', 'id_estado' => 2 ],
            [ 'id_municipio' => 12 , 'nombre' =>'Clarines', 'id_estado' => 2 ],
            [ 'id_municipio' => 13 , 'nombre' =>'El Chaparro', 'id_estado' => 2 ],
            [ 'id_municipio' => 14 , 'nombre' =>'Fría', 'id_estado' => 2 ],
            [ 'id_municipio' => 15 , 'nombre' =>'Guanta', 'id_estado' => 2 ],
            [ 'id_municipio' => 16 , 'nombre' =>'Independencia', 'id_estado' => 2 ],
            [ 'id_municipio' => 17 , 'nombre' =>'José Gregorio Monagas', 'id_estado' => 2 ],
            [ 'id_municipio' => 18 , 'nombre' =>'Juan Antonio Sotillo', 'id_estado' => 2 ],
            [ 'id_municipio' => 19 , 'nombre' =>'Juan José Flores', 'id_estado' => 2 ],
            [ 'id_municipio' => 20 , 'nombre' =>'MRZ de Barcelona', 'id_estado' => 2 ],
            [ 'id_municipio' => 21 , 'nombre' =>'Miranda', 'id_estado' => 2 ],
            [ 'id_municipio' => 22 , 'nombre' =>'Montes', 'id_estado' => 2 ],
            [ 'id_municipio' => 23 , 'nombre' =>'Urbaneja', 'id_estado' => 2 ],
            [ 'id_municipio' => 24 , 'nombre' =>'Valdez', 'id_estado' => 2 ],
            [ 'id_municipio' => 25 , 'nombre' =>'Achaguas', 'id_estado' => 3 ],
            [ 'id_municipio' => 26 , 'nombre' =>'Biruaca', 'id_estado' => 3 ],
            [ 'id_municipio' => 27 , 'nombre' =>'Muñoz', 'id_estado' => 3 ],
            [ 'id_municipio' => 28 , 'nombre' =>'Pedro Camejo', 'id_estado' => 3 ],
            [ 'id_municipio' => 29 , 'nombre' =>'Rómulo Gallegos', 'id_estado' => 3 ],
            [ 'id_municipio' => 30 , 'nombre' =>'San Fernando de Apure', 'id_estado' => 3 ],
            [ 'id_municipio' => 31 , 'nombre' =>'San Juan de Payara', 'id_estado' => 3 ],
            [ 'id_municipio' => 32 , 'nombre' =>'Sebastian Francisco de Miranda', 'id_estado' => 3 ],
            [ 'id_municipio' => 33 , 'nombre' =>'Pedro Pablo Gutiérrez', 'id_estado' => 3 ],
            [ 'id_municipio' => 34 , 'nombre' =>'Sosa', 'id_estado' => 3 ],
            [ 'id_municipio' => 35 , 'nombre' =>'Augusto M. García', 'id_estado' => 4 ],
            [ 'id_municipio' => 36 , 'nombre' =>'Bolívar', 'id_estado' => 4 ],
            [ 'id_municipio' => 37 , 'nombre' =>'Camatagua', 'id_estado' => 4 ],
            [ 'id_municipio' => 38 , 'nombre' =>'Girardot', 'id_estado' => 4 ],
            [ 'id_municipio' => 39 , 'nombre' =>'José Ángel Lamas', 'id_estado' => 4 ],
            [ 'id_municipio' => 40 , 'nombre' =>'José Félix Ribas', 'id_estado' => 4 ],
            [ 'id_municipio' => 41 , 'nombre' =>'Mario Briceño Iragorry', 'id_estado' => 4 ],
            [ 'id_municipio' => 42 , 'nombre' =>'Ocumare de la Costa', 'id_estado' => 4 ],
            [ 'id_municipio' => 43 , 'nombre' =>'San Casimiro', 'id_estado' => 4 ],
            [ 'id_municipio' => 44 , 'nombre' =>'San Sebastián', 'id_estado' => 4 ],
            [ 'id_municipio' => 45 , 'nombre' =>'Santiago Mariño', 'id_estado' => 4 ],
            [ 'id_municipio' => 46 , 'nombre' =>'Sucre', 'id_estado' => 4 ],
            [ 'id_municipio' => 47 , 'nombre' =>'Tovar', 'id_estado' => 4 ],
            [ 'id_municipio' => 48 , 'nombre' =>'Zamora', 'id_estado' => 4 ],
            [ 'id_municipio' => 49 , 'nombre' =>'Alberdi', 'id_estado' => 5 ],
            [ 'id_municipio' => 50 , 'nombre' =>'Barinas', 'id_estado' => 5 ],
            [ 'id_municipio' => 51 , 'nombre' =>'Bolívar', 'id_estado' => 5 ],
            [ 'id_municipio' => 52 , 'nombre' =>'Cadena', 'id_estado' => 5 ],
            [ 'id_municipio' => 53 , 'nombre' =>'Bolívar', 'id_estado' => 5 ],
            [ 'id_municipio' => 54 , 'nombre' =>'Pedraza', 'id_estado' => 5 ],
            [ 'id_municipio' => 55 , 'nombre' =>'Sosa', 'id_estado' => 5 ],
            [ 'id_municipio' => 56 , 'nombre' =>'Torbes', 'id_estado' => 5 ],
            [ 'id_municipio' => 57 , 'nombre' =>'Angostura', 'id_estado' => 6 ],
            [ 'id_municipio' => 58 , 'nombre' =>'Bolivar', 'id_estado' => 6 ],
            [ 'id_municipio' => 59 , 'nombre' =>'Cedeño', 'id_estado' => 6 ],
            [ 'id_municipio' => 60 , 'nombre' =>'Ciudad Bolívar', 'id_estado' => 6 ],
            [ 'id_municipio' => 61 , 'nombre' =>'El Callao', 'id_estado' => 6 ],
            [ 'id_municipio' => 62 , 'nombre' =>'Gran Sabana', 'id_estado' => 6 ],
            [ 'id_municipio' => 63 , 'nombre' =>'Sifontes', 'id_estado' => 6 ],
            [ 'id_municipio' => 64 , 'nombre' =>'Saza', 'id_estado' => 6 ],
            [ 'id_municipio' => 65 , 'nombre' =>'Padre Chorrera', 'id_estado' => 6 ],
            [ 'id_municipio' => 66 , 'nombre' =>'Turnu', 'id_estado' => 6 ],
            [ 'id_municipio' => 67 , 'nombre' =>'Bejuma', 'id_estado' => 7 ],
            [ 'id_municipio' => 68 , 'nombre' =>'Carlos Arvelo', 'id_estado' => 7 ],
            [ 'id_municipio' => 69 , 'nombre' =>'Diego Ibarra', 'id_estado' => 7 ],
            [ 'id_municipio' => 70 , 'nombre' =>'Guacara', 'id_estado' => 7 ],
            [ 'id_municipio' => 71 , 'nombre' =>'Juan José Mora', 'id_estado' => 7 ],
            [ 'id_municipio' => 72 , 'nombre' =>'Libertador', 'id_estado' => 7 ],
            [ 'id_municipio' => 73 , 'nombre' =>'Los Guayos', 'id_estado' => 7 ],
            [ 'id_municipio' => 74 , 'nombre' =>'Miranda', 'id_estado' => 7 ],
            [ 'id_municipio' => 75 , 'nombre' =>'Montalbán', 'id_estado' => 7 ],
            [ 'id_municipio' => 76 , 'nombre' =>'Naguanagua', 'id_estado' => 7 ],
            [ 'id_municipio' => 77 , 'nombre' =>'Puerto Cabello', 'id_estado' => 7 ],
            [ 'id_municipio' => 78 , 'nombre' =>'San Diego', 'id_estado' => 7 ],
            [ 'id_municipio' => 79 , 'nombre' =>'San Joaquín', 'id_estado' => 7 ],
            [ 'id_municipio' => 80 , 'nombre' =>'Valencia', 'id_estado' => 7 ],
            [ 'id_municipio' => 81 , 'nombre' =>'Anzoátegui', 'id_estado' => 8 ],
            [ 'id_municipio' => 82 , 'nombre' =>'Ezequiel Zamora', 'id_estado' => 8 ],
            [ 'id_municipio' => 83 , 'nombre' =>'Fomento', 'id_estado' => 8 ],
            [ 'id_municipio' => 84 , 'nombre' =>'Girardot', 'id_estado' => 8 ],
            [ 'id_municipio' => 85 , 'nombre' =>'Pao de San Juan Bautista', 'id_estado' => 8 ],
            [ 'id_municipio' => 86 , 'nombre' =>'Rómulo Gallegos', 'id_estado' => 8 ],
            [ 'id_municipio' => 87 , 'nombre' =>'Tinaco', 'id_estado' => 8 ],
            [ 'id_municipio' => 88 , 'nombre' =>'Antonio Díaz', 'id_estado' => 9 ],
            [ 'id_municipio' => 89 , 'nombre' =>'Casacoima', 'id_estado' => 9 ],
            [ 'id_municipio' => 90 , 'nombre' =>'Pedernales', 'id_estado' => 9 ],
            [ 'id_municipio' => 91 , 'nombre' =>'Tucupita', 'id_estado' => 9 ],
            [ 'id_municipio' => 92 , 'nombre' =>'Acosta', 'id_estado' => 10 ],
            [ 'id_municipio' => 93 , 'nombre' =>'Federación', 'id_estado' => 10 ],
            [ 'id_municipio' => 94 , 'nombre' =>'Falcón', 'id_estado' => 10 ],
            [ 'id_municipio' => 95 , 'nombre' =>'Jacura', 'id_estado' => 10 ],
            [ 'id_municipio' => 96 , 'nombre' =>'Mauroa', 'id_estado' => 10 ],
            [ 'id_municipio' => 97 , 'nombre' =>'Miranda', 'id_estado' => 10 ],
            [ 'id_municipio' => 98 , 'nombre' =>'Monseñor', 'id_estado' => 10 ],
            [ 'id_municipio' => 99 , 'nombre' =>'Palmasola', 'id_estado' => 10 ],
            [ 'id_municipio' => 100 , 'nombre' =>'Píritu', 'id_estado' => 10 ],
            [ 'id_municipio' => 101 , 'nombre' =>'San Francisco', 'id_estado' => 10 ],
            [ 'id_municipio' => 102 , 'nombre' =>'Silva', 'id_estado' => 10 ],
            [ 'id_municipio' => 103 , 'nombre' =>'Tocópero', 'id_estado' => 10 ],
            [ 'id_municipio' => 104 , 'nombre' =>'Urumaco', 'id_estado' => 10 ],
            [ 'id_municipio' => 105 , 'nombre' =>'Zamora', 'id_estado' => 10 ],
            [ 'id_municipio' => 106 , 'nombre' =>'infantil (Zaraza)', 'id_estado' => 11 ],
            [ 'id_municipio' => 107 , 'nombre' =>'Camaguan', 'id_estado' => 11 ],
            [ 'id_municipio' => 108 , 'nombre' =>'Chaguaramas', 'id_estado' => 11 ],
            [ 'id_municipio' => 109 , 'nombre' =>'El Socorro', 'id_estado' => 11 ],
            [ 'id_municipio' => 110 , 'nombre' =>'Francisco de Miranda', 'id_estado' => 11 ],
            [ 'id_municipio' => 111 , 'nombre' =>'José Félix Ribas', 'id_estado' => 11 ],
            [ 'id_municipio' => 112 , 'nombre' =>'Las Mercedes', 'id_estado' => 11 ],
            [ 'id_municipio' => 113 , 'nombre' =>'Leonardo Infante', 'id_estado' => 11 ],
            [ 'id_municipio' => 114 , 'nombre' =>'Juan Germán Roscio', 'id_estado' => 11 ],
            [ 'id_municipio' => 115 , 'nombre' =>'Julián Mellado', 'id_estado' => 11 ],
            [ 'id_municipio' => 116 , 'nombre' =>'Ortiz', 'id_estado' => 11 ],
            [ 'id_municipio' => 117 , 'nombre' =>'San José de Guaribe', 'id_estado' => 11 ],
            [ 'id_municipio' => 118 , 'nombre' =>'Santa María de Ipire', 'id_estado' => 11 ],
            [ 'id_municipio' => 119 , 'nombre' =>'Andrés Eloy Blanco', 'id_estado' => 12 ],
            [ 'id_municipio' => 120 , 'nombre' =>'Bettencourt', 'id_estado' => 12 ],
            [ 'id_municipio' => 121 , 'nombre' =>'Crespo', 'id_estado' => 12 ],
            [ 'id_municipio' => 122 , 'nombre' =>'Iribarren', 'id_estado' => 12 ],
            [ 'id_municipio' => 123 , 'nombre' =>'Jiménez', 'id_estado' => 12 ],
            [ 'id_municipio' => 124 , 'nombre' =>'Morán', 'id_estado' => 12 ],
            [ 'id_municipio' => 125 , 'nombre' =>'Palavecino', 'id_estado' => 12 ],
            [ 'id_municipio' => 126 , 'nombre' =>'Simón Planas', 'id_estado' => 12 ],
            [ 'id_municipio' => 127 , 'nombre' =>'Torres', 'id_estado' => 12 ],
            [ 'id_municipio' => 128 , 'nombre' =>'Urdaneta', 'id_estado' => 12 ],
            [ 'id_municipio' => 129 , 'nombre' =>'Alberto Adriani', 'id_estado' => 13 ],
            [ 'id_municipio' => 130 , 'nombre' =>'Alberto de la Vega', 'id_estado' => 13 ],
            [ 'id_municipio' => 131 , 'nombre' =>'Campo Elías', 'id_estado' => 13 ],
            [ 'id_municipio' => 132 , 'nombre' =>'Caracciolo Parra Pérez', 'id_estado' => 13 ],
            [ 'id_municipio' => 133 , 'nombre' =>'Guaraque', 'id_estado' => 13 ],
            [ 'id_municipio' => 134 , 'nombre' =>'Libertador', 'id_estado' => 13 ],
            [ 'id_municipio' => 135 , 'nombre' =>'Miranda', 'id_estado' => 13 ],
            [ 'id_municipio' => 136 , 'nombre' =>'Rangel', 'id_estado' => 13 ],
            [ 'id_municipio' => 137 , 'nombre' =>'Sucre', 'id_estado' => 13 ],
            [ 'id_municipio' => 138 , 'nombre' =>'Zea', 'id_estado' => 13 ],
            [ 'id_municipio' => 139 , 'nombre' =>'Acevedo', 'id_estado' => 14 ],
            [ 'id_municipio' => 140 , 'nombre' =>'Brión', 'id_estado' => 14 ],
            [ 'id_municipio' => 141 , 'nombre' =>'Buroz', 'id_estado' => 14 ],
            [ 'id_municipio' => 142 , 'nombre' =>'Carrizal', 'id_estado' => 14 ],
            [ 'id_municipio' => 143 , 'nombre' =>'Cristóbal Rojas', 'id_estado' => 14 ],
            [ 'id_municipio' => 144 , 'nombre' =>'Guaicaipuro', 'id_estado' => 14 ],
            [ 'id_municipio' => 145 , 'nombre' =>'Independencia', 'id_estado' => 14 ],
            [ 'id_municipio' => 146 , 'nombre' =>'Lander', 'id_estado' => 14 ],
            [ 'id_municipio' => 147 , 'nombre' =>'Los Salias', 'id_estado' => 14 ],
            [ 'id_municipio' => 148 , 'nombre' =>'Páez', 'id_estado' => 14 ],
            [ 'id_municipio' => 149 , 'nombre' =>'Paz Castillo', 'id_estado' => 14 ],
            [ 'id_municipio' => 150 , 'nombre' =>'Pedro Gual', 'id_estado' => 14 ],
            [ 'id_municipio' => 151 , 'nombre' =>'Plaza', 'id_estado' => 14 ],
            [ 'id_municipio' => 152 , 'nombre' =>'Urdaneta', 'id_estado' => 14 ],
            [ 'id_municipio' => 153 , 'nombre' =>'Zamora', 'id_estado' => 14 ],
            [ 'id_municipio' => 154 , 'nombre' =>'Acosta', 'id_estado' => 15 ],
            [ 'id_municipio' => 155 , 'nombre' =>'Aguasay', 'id_estado' => 15 ],
            [ 'id_municipio' => 156 , 'nombre' =>'Bolívar', 'id_estado' => 15 ],
            [ 'id_municipio' => 157 , 'nombre' =>'Caripe', 'id_estado' => 15 ],
            [ 'id_municipio' => 158 , 'nombre' =>'Cedeño', 'id_estado' => 15 ],
            [ 'id_municipio' => 159 , 'nombre' =>'Ezequiel Zamora', 'id_estado' => 15 ],
            [ 'id_municipio' => 160 , 'nombre' =>'Libertador', 'id_estado' => 15 ],
            [ 'id_municipio' => 161 , 'nombre' =>'Maturín', 'id_estado' => 15 ],
            [ 'id_municipio' => 162 , 'nombre' =>'Piar', 'id_estado' => 15 ],
            [ 'id_municipio' => 163 , 'nombre' =>'Punceres', 'id_estado' => 15 ],
            [ 'id_municipio' => 164 , 'nombre' =>'Santa Bárbara', 'id_estado' => 15 ],
            [ 'id_municipio' => 165 , 'nombre' =>'Sotillo', 'id_estado' => 15 ],
            [ 'id_municipio' => 166 , 'nombre' =>'Uracoa', 'id_estado' => 15 ],
            [ 'id_municipio' => 167 , 'nombre' =>'Antolín del Campo', 'id_estado' => 16 ],
            [ 'id_municipio' => 168 , 'nombre' =>'Arismendi', 'id_estado' => 16 ],
            [ 'id_municipio' => 169 , 'nombre' =>'Díaz', 'id_estado' => 16 ],
            [ 'id_municipio' => 170 , 'nombre' =>'García', 'id_estado' => 16 ],
            [ 'id_municipio' => 171 , 'nombre' =>'Gómez', 'id_estado' => 16 ],
            [ 'id_municipio' => 172 , 'nombre' =>'Maneiro', 'id_estado' => 16 ],
            [ 'id_municipio' => 173 , 'nombre' =>'Marcano', 'id_estado' => 16 ],
            [ 'id_municipio' => 174 , 'nombre' =>'Mariño', 'id_estado' => 16 ],
            [ 'id_municipio' => 175 , 'nombre' =>'Valdez', 'id_estado' => 16 ],
            [ 'id_municipio' => 176 , 'nombre' =>'Villalba', 'id_estado' => 16 ],
            [ 'id_municipio' => 177 , 'nombre' =>'Agua Blanca', 'id_estado' => 17 ],
            [ 'id_municipio' => 178 , 'nombre' =>'Araure', 'id_estado' => 17 ],
            [ 'id_municipio' => 179 , 'nombre' =>'Esteller', 'id_estado' => 17 ],
            [ 'id_municipio' => 180 , 'nombre' =>'Guanare', 'id_estado' => 17 ],
            [ 'id_municipio' => 181 , 'nombre' =>'Páez', 'id_estado' => 17 ],
            [ 'id_municipio' => 182 , 'nombre' =>'San Rafael de Onoto', 'id_estado' => 17 ],
            [ 'id_municipio' => 183 , 'nombre' =>'Turén', 'id_estado' => 17 ],
            [ 'id_municipio' => 184 , 'nombre' =>'Bermúdez', 'id_estado' => 18 ],
            [ 'id_municipio' => 185 , 'nombre' =>'Frías', 'id_estado' => 18 ],
            [ 'id_municipio' => 186 , 'nombre' =>'Bolívar', 'id_estado' => 18 ],
            [ 'id_municipio' => 187 , 'nombre' =>'Libertador', 'id_estado' => 18 ],
            [ 'id_municipio' => 188 , 'nombre' =>'Mariño', 'id_estado' => 18 ],
            [ 'id_municipio' => 189 , 'nombre' =>'Mejía', 'id_estado' => 18 ],
            [ 'id_municipio' => 190 , 'nombre' =>'Ribero', 'id_estado' => 18 ],
            [ 'id_municipio' => 191 , 'nombre' =>'Sucre', 'id_estado' => 18 ],
            [ 'id_municipio' => 192 , 'nombre' =>'Valdez', 'id_estado' => 18 ],
            [ 'id_municipio' => 193 , 'nombre' =>'Ayala', 'id_estado' => 19 ],
            [ 'id_municipio' => 194 , 'nombre' =>'Córdoba', 'id_estado' => 19 ],
            [ 'id_municipio' => 195 , 'nombre' =>'Fernández Feo', 'id_estado' => 19 ],
            [ 'id_municipio' => 196 , 'nombre' =>'García de Hevia', 'id_estado' => 19 ],
            [ 'id_municipio' => 197 , 'nombre' =>'Guásimos', 'id_estado' => 19 ],
            [ 'id_municipio' => 198 , 'nombre' =>'José María Vargas', 'id_estado' => 19 ],
            [ 'id_municipio' => 199 , 'nombre' =>'Junín', 'id_estado' => 19 ],
            [ 'id_municipio' => 200 , 'nombre' =>'Libertad', 'id_estado' => 19 ],
            [ 'id_municipio' => 201 , 'nombre' =>'Michelena', 'id_estado' => 19 ],
            [ 'id_municipio' => 202 , 'nombre' =>'Panamericano', 'id_estado' => 19 ],
            [ 'id_municipio' => 203 , 'nombre' =>'Pedro María Morantes', 'id_estado' => 19 ],
            [ 'id_municipio' => 204 , 'nombre' =>'San Judas Tadeo', 'id_estado' => 19 ],
            [ 'id_municipio' => 205 , 'nombre' =>'Simón Rodríguez', 'id_estado' => 19 ],
            [ 'id_municipio' => 206 , 'nombre' =>'Sucre', 'id_estado' => 19 ],
            [ 'id_municipio' => 207 , 'nombre' =>'Torbes', 'id_estado' => 19 ],
            [ 'id_municipio' => 208 , 'nombre' =>'Rubio', 'id_estado' => 19 ],
            [ 'id_municipio' => 209 , 'nombre' =>'Andrés Bello', 'id_estado' => 20 ],
            [ 'id_municipio' => 210 , 'nombre' =>'Boconó', 'id_estado' => 20 ],
            [ 'id_municipio' => 211 , 'nombre' =>'Bolivar', 'id_estado' => 20 ],
            [ 'id_municipio' => 212 , 'nombre' =>'Candelaria', 'id_estado' => 20 ],
            [ 'id_municipio' => 213 , 'nombre' =>'Carlos Caribe', 'id_estado' => 20 ],
            [ 'id_municipio' => 214 , 'nombre' =>'Frank Paz', 'id_estado' => 20 ],
            [ 'id_municipio' => 215 , 'nombre' =>'Jacinto Plaza', 'id_estado' => 20 ],
            [ 'id_municipio' => 216 , 'nombre' =>'Juan Antonio Sotillo', 'id_estado' => 20 ],
            [ 'id_municipio' => 217 , 'nombre' =>'La Ceiba', 'id_estado' => 20 ],
            [ 'id_municipio' => 218 , 'nombre' =>'Miranda', 'id_estado' => 20 ],
            [ 'id_municipio' => 219 , 'nombre' =>'Pampán', 'id_estado' => 20 ],
            [ 'id_municipio' => 220 , 'nombre' =>'Trujillo', 'id_estado' => 20 ],
            [ 'id_municipio' => 221 , 'nombre' =>'Valera', 'id_estado' => 20 ],
            [ 'id_municipio' => 222 , 'nombre' =>'Caraballeda', 'id_estado' => 21 ],
            [ 'id_municipio' => 223 , 'nombre' =>'Catia La Mar', 'id_estado' => 21 ],
            [ 'id_municipio' => 224 , 'nombre' =>'La Guaira', 'id_estado' => 21 ],
            [ 'id_municipio' => 225 , 'nombre' =>'Naiguatá', 'id_estado' => 21 ],
            [ 'id_municipio' => 226 , 'nombre' =>'Macuto', 'id_estado' => 21 ],
            [ 'id_municipio' => 227 , 'nombre' =>'Urimare', 'id_estado' => 21 ],
            [ 'id_municipio' => 228 , 'nombre' =>'Arístides Bastidas', 'id_estado' => 22 ],
            [ 'id_municipio' => 229 , 'nombre' =>'Bolívar', 'id_estado' => 22 ],
            [ 'id_municipio' => 230 , 'nombre' =>'Bruzual', 'id_estado' => 22 ],
            [ 'id_municipio' => 231 , 'nombre' =>'Cocorote', 'id_estado' => 22 ],
            [ 'id_municipio' => 232 , 'nombre' =>'Independencia', 'id_estado' => 22 ],
            [ 'id_municipio' => 233 , 'nombre' =>'José Antonio Páez', 'id_estado' => 22 ],
            [ 'id_municipio' => 234 , 'nombre' =>'La Trinidad', 'id_estado' => 22 ],
            [ 'id_municipio' => 235 , 'nombre' =>'Manuel Monge', 'id_estado' => 22 ],
            [ 'id_municipio' => 236 , 'nombre' =>'Nirgua', 'id_estado' => 22 ],
            [ 'id_municipio' => 237 , 'nombre' =>'San Felipe', 'id_estado' => 22 ],
            [ 'id_municipio' => 238 , 'nombre' =>'Yaritagua', 'id_estado' => 22 ],
            [ 'id_municipio' => 239 , 'nombre' =>'Almirante Padilla', 'id_estado' => 23 ],
            [ 'id_municipio' => 240 , 'nombre' =>'Cabimas', 'id_estado' => 23 ],
            [ 'id_municipio' => 241 , 'nombre' =>'Catatumbo', 'id_estado' => 23 ],
            [ 'id_municipio' => 242 , 'nombre' =>'Colón', 'id_estado' => 23 ],
            [ 'id_municipio' => 243 , 'nombre' =>'Francisco Javier Pulgar', 'id_estado' => 23 ],
            [ 'id_municipio' => 244 , 'nombre' =>'Jesús Enrique Losada', 'id_estado' => 23 ],
            [ 'id_municipio' => 245 , 'nombre' =>'Jesús María Semprún', 'id_estado' => 23 ],
            [ 'id_municipio' => 246 , 'nombre' =>'Machiques de Perijá', 'id_estado' => 23 ],
            [ 'id_municipio' => 247 , 'nombre' =>'Mara', 'id_estado' => 23 ],
            [ 'id_municipio' => 248 , 'nombre' =>'Maracaibo', 'id_estado' => 23 ],
            [ 'id_municipio' => 249 , 'nombre' =>'Rosario de Perijá', 'id_estado' => 23 ],
            [ 'id_municipio' => 250 , 'nombre' =>'San Francisco', 'id_estado' => 23 ],
            [ 'id_municipio' => 251 , 'nombre' =>'Santa Rita', 'id_estado' => 23 ],
            [ 'id_municipio' => 252 , 'nombre' =>'Simón Bolívar', 'id_estado' => 23 ],
            [ 'id_municipio' => 253 , 'nombre' =>'Suarez', 'id_estado' => 23 ],
            [ 'id_municipio' => 254 , 'nombre' =>'Libertador', 'id_estado' => 24 ],
            [ 'id_municipio' => 255 , 'nombre' =>'Baruta', 'id_estado' => 24 ],
            [ 'id_municipio' => 256 , 'nombre' =>'Chacao', 'id_estado' => 24 ],
            [ 'id_municipio' => 257 , 'nombre' =>'El Hatillo', 'id_estado' => 24 ],
            [ 'id_municipio' => 258 , 'nombre' =>'Sucre', 'id_estado' => 24 ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('municipios');
    }
};
